spring:
  security:
    oauth2:
      client:
        provider:
          okta:
            user-name-attribute: email

okta:
  oauth2:
    redirect-uri: /authorization-code/callback
    scopes:
    - profile
    - email
    - openid
    client-id: 
    client-secret: 
    issuer: https://******.okta.com/oauth2/default
    post-logout-redirect-uri: http://localhost:8080/
    
    
    
